// Generated by CoffeeScript 1.6.1
(function() {
  var sumatra,
    _this = this;

  this.SumatraPlugin = (function() {

    SumatraPlugin.prototype.action = 'one';

    SumatraPlugin.prototype.defaults = {};

    function SumatraPlugin(current_element, index_of_query, init_options) {
      var _this = this;
      this.perform = function(event) {
        return SumatraPlugin.prototype.perform.apply(_this, arguments);
      };
      this.element = $(current_element);
      this.index = index_of_query;
      this.options = init_options;
      this.mergeOptions() && this.initialize() && this.bindEvents();
    }

    SumatraPlugin.prototype.mergeOptions = function() {
      var _;
      _ = require('underscore');
      return this.options = _.extend(this.defaults, this.options);
    };

    SumatraPlugin.prototype.initialize = function() {
      return true;
    };

    SumatraPlugin.prototype.bindEvents = function() {
      if (this.action != null) {
        return this.element.on(this.action, this.perform);
      }
    };

    SumatraPlugin.prototype.perform = function(event) {
      var target;
      target = event.currentTarget;
      throw "Error: `" + target + "` has no event binding for '" + action + "'.";
    };

    return SumatraPlugin;

  })();

  sumatra = function(plugin_name, plugin_code) {
    var plugin_helper,
      _this = this;
    plugin_helper = plugin_code.apply(this);
    return jQuery.fn[plugin_name](function() {
      return _this.each(function(index, element) {
        return new plugin_helper(element, index);
      });
    });
  };

}).call(this);
