// Generated by CoffeeScript 1.6.1
(function() {

  this.SumatraPlugin = (function() {

    SumatraPlugin.prototype.action = 'one';

    SumatraPlugin.prototype.defaults = {};

    function SumatraPlugin(current_element, index_of_query, init_options) {
      this.element = $(current_element);
      this.index = index_of_query;
      this.options = this.mergeDefaultsWith(init_options);
      this.initialize() && this.bindEvents();
    }

    SumatraPlugin.prototype.mergeDefaultsWith = function(options) {
      return _.extend(this.defaults, this.options);
    };

    SumatraPlugin.prototype.initialize = function() {
      return true;
    };

    SumatraPlugin.prototype.bindEvents = function() {
      if (this.action != null) {
        return this.element.on(this.action, this.perform);
      }
    };

    return SumatraPlugin;

  })();

  this.sumatra = function(plugin_name, plugin_code) {
    var PluginHelper;
    PluginHelper = plugin_code.apply(this);
    return jQuery.fn[plugin_name] = function(options) {
      if (options == null) {
        options = {};
      }
      return this.each(function(index, element) {
        return new PluginHelper(element, index, options);
      });
    };
  };

}).call(this);
